### ISSUE TITLE
Allow empty times in event Start/End

### ISSUE THREAD

**Issue by tardinha** [nglasl/silverstripe-mediawesome#10]
Some events run for multiple days/weels/months etc, and so don't have start/end times.

When saving an event without start/end times specified, it defaults to 12:00:00 AM.

It would be awesome if they could be left blank.

**Comment by nglasl** [comment]
I'm pretty sure this is default SS behaviour, where a date time field is saved into the database as `xxxx-xx-xx 00:00:00`. I'll have a look at a couple of options. Does event calendar do anything around this, or does it just use an "is all day" flag?

**Comment by tardinha** [comment]
Event Calendar has separate Date and Time fields :)

**Comment by nglasl** [comment]
Okay, so I've now split these out into separate date and time fields, while correcting some issues where new media attributes weren't being detected as expected. I'm yet to create a new tag, as I have some further tweaks coming that I'm going to bundle together. I'll get back to you when they're all ready to go out, so there's nothing to do just at the moment.
