### ISSUE TITLE
MediaHolder should default to first MediaType.

### ISSUE THREAD

**Issue by silbinarywolf** [nglasl/silverstripe-mediawesome#16]
**The problem:**
When creating a MediaHolder and child MediaPages, the logic in MediaPage::onBeforeWrite sets the parents MediaType if its not equal, but does not handle publishing correctly. (At least in Silverstripe 3.X)

So you end up with validation issues when you attempt to publish MediaPage (via a dev/task)

**The solution:**
- MediaHolder should default to first MediaType.
- MediaPage should *ideally* not write/change the state of its parent at all. We should avoid this complexity if we can. For both SS3 and SS4.

**Comment by nglasl** [comment]
I've opted to change this for only SS4 right now, since this is the primary version moving forwards, and it's only an issue in SS3 under specific circumstances (that can be worked around).
