### ISSUE TITLE
Custom form fields aren't loaded with data after searching

### ISSUE THREAD

**Issue by silbinarywolf** [nglasl/silverstripe-mediawesome#17]
**The problem**
In my SilverStripe 3.6 project, I've added additional custom filtering fields to the form using extensions. When you filter however, those values aren't retained in the form.

This is due to the following line not occuring after the extension point:
https://github.com/nglasl/silverstripe-mediawesome/blob/master/src/controllers/MediaHolderController.php#L434
`$form->loadDataFrom($request->getVars());`

**The solution**
Move `$form->loadDataFrom($request->getVars());` to be after the extension point.

**Affected versions**
- 2.0+
- 3.0+
- 4.0+

**Comment by nglasl** [comment]
Thanks for throwing this one through! I've solved it for SS4 with the above commit, and plan on making the change in the SS3 line too.
