### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by blouloudakis** [nglasl/silverstripe-mediawesome#19]
The error message doesnt provide enough explanation as to what youre doing incorrectly. 
Eg. i moved a news media typer article under and an event media type page, and received the error message "Incorrect media holder" but it should have been something along the lines of Media Type doesnt match Media Holder type"

**Comment by nglasl** [comment]
Hey @blouloudakis, this is now improved in https://github.com/nglasl/silverstripe-mediawesome/commit/4e7dde685ab669015380def521e0030f23bdd82b for SS4.
