### ISSUE TITLE
Custom media attributes not available to Content Authors

### ISSUE THREAD

**Issue by jenniferaslan** [nglasl/silverstripe-mediawesome#20]
When using the CMS as a Content Author user (rather than an Administrator), the custom media attributes are not available to use on a Media Page under a Publication Media Holder. I have not tested the other types of Media Holders.

**Comment by nglasl** [comment]
Thanks for the heads up. Having a quick look, this one looks to be due to the SS4 change from `MediaAttribute` to `MediaPageAttribute`. I tried adding a simple `canView` to this and they're now appearing, but I need to spend a little more time investigating what the proper solution is here.

**Comment by nglasl** [comment]
If this issue still applies, can you please open it on https://github.com/symbiote/silverstripe-mediawesome which will be the source of truth moving forwards.
