### ISSUE TITLE
SQL error when using postgres db

### ISSUE THREAD

**Issue by surf9** [nglasl/silverstripe-mediawesome#23]
Hi there

When I try to do a dev/build/flush=1 I get the following warning/error messages using silverstripe version 3.7 using the postgres module. As a result the module does not get properly installed.

[Warning] pg_query_params(): Query failed: ERROR: missing FROM-clause entry for table "mediaattribute" LINE 4: FROM "MediaAttribute" INNER JOIN "MediaPage" ON MediaAttrib... ^
GET /dev/build?devbuildtoken=38f26c41a2fe11a6c609e2faa1b7de8c&flush=1&flushtoken=3536018115612fd551c88ae77a321679
Line 200 in /opt/silverstripe/project/docroot/postgresql/code/PostgreSQLConnector.php

and

[User Error] Uncaught SS_DatabaseException: Couldn't run query: SELECT DISTINCT "MediaAttribute"."ClassName", "MediaAttribute"."LastEdited", "MediaAttribute"."Created", "MediaAttribute"."OriginalTitle", "MediaAttribute"."Title", "MediaAttribute"."Content", "MediaAttribute"."LinkID", "MediaAttribute"."MediaPageID", "MediaAttribute"."ID", CASE WHEN "MediaAttribute"."ClassName" IS NOT NULL THEN "MediaAttribute"."ClassName" ELSE 'MediaAttribute' END AS "RecordClassName" FROM "MediaAttribute" INNER JOIN "MediaPage" ON MediaAttribute.MediaPageID = MediaPage.ID INNER JOIN "MediaType" ON MediaPage.MediaTypeID = MediaType.ID WHERE (MediaType.Title = $1) AND (OriginalTitle = $2) ERROR: missing FROM-clause entry for table "mediaattribute" LINE 4: FROM "MediaAttribute" INNER JOIN "MediaPage" ON MediaAttrib... ^
GET /dev/build?devbuildtoken=38f26c41a2fe11a6c609e2faa1b7de8c&flush=1&flushtoken=3536018115612fd551c88ae77a321679
Line 55 in /opt/silverstripe/project/docroot/framework/model/connect/DBConnector.php

What can be done to resolve this?

Cheers

**Comment by nglasl** [comment]
If this issue still applies, can you please open it on https://github.com/symbiote/silverstripe-mediawesome which will be the source of truth moving forwards.
