### ISSUE TITLE
[Warning] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by AlphaCactus** [nglasl/silverstripe-mediawesome#25]
On `/dev/build` with PHP 7.2
```
[Warning] count(): Parameter must be an array or an object that implements Countable
GET /dev/build
Line 127 in vendor/nglasl/silverstripe-mediawesome/src/pages/MediaPage.php
```

From https://stackoverflow.com/a/51594954/2045153
> PDO fetch returns false on failure. So you need to check this case too

**Comment by nglasl** [comment]
If this issue still applies, can you please open it on https://github.com/symbiote/silverstripe-mediawesome which will be the source of truth moving forwards.
