### ISSUE TITLE
MediaPage extends SiteTree, causing it to not integrate with Solr automatically.

### ISSUE THREAD

**Issue by SilbinaryWolf** [nglasl/silverstripe-mediawesome#8]
Is there any particular reason why MediaPage extends SiteTree and not Page?

This has the potential to cause a lot more issues with other extensions, not just Solr.

**Comment by tardinha** [comment]
Seconded...

**Comment by nglasl** [comment]
This now extends page rather than site tree. I will be doing some testing with this before pushing a stable tag.
