### ISSUE TITLE
PaginatedChildren returning duplicates in template

### ISSUE THREAD

**Issue by tardinha** [nglasl/silverstripe-mediawesome#9]
Adjusting the number of tems returned perhape via $PaginatedChildren(10) causes repeat items on each page.

Setting the limit in PHp works fine.

**Comment by nglasl** [comment]
Okay, so after having a poke around, this one is actually a problem with the template. When replacing `$PaginatedChildren` with `$PaginatedChildren(10)`, you'll also need to update other references such as `$PaginatedChildren.NextLink` to `$PaginatedChildren(10).NextLink`. These are still being limited to 5 results by default, and therefore are causing `?start=5` to be appended to the URL (causing duplicate results). Please let me know if you have any further questions on this one :)
